class ZavoraCli < Formula
  desc "Rust CLI agent shell built on ADK-Rust"
  homepage "https://github.com/zavora-ai/zavora-cli"
  url "https://github.com/zavora-ai/zavora-cli/archive/refs/tags/v2.0.0.tar.gz"
  # Regenerated by scripts/generate_homebrew_formula.sh during release, once the
  # tag archive exists and its digest can be computed. `make version-check`
  # verifies that the version above matches Cargo.toml and the npm package.
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", *std_cargo_args(path: ".")
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/zavora-cli --help")
  end
end
