pub mod agent_catalog;
pub mod agents;
pub mod capabilities;
pub mod chat;
pub mod checkpoint;
pub mod cli;
pub mod compact;
pub mod config;
pub mod context;
pub mod credentials;
pub mod doctor;
pub mod error;
pub mod eval;
pub mod file_history;
pub mod guardrail;
pub mod headless;
pub mod hooks;
pub mod lsp;
pub mod markdown;
pub mod mcp;
pub mod mcp_auth;
pub mod mcp_catalog;
pub mod mcp_server;
pub mod model_catalog;
pub mod model_roles;
pub mod onboarding;
pub mod plugins;
pub mod profiles;
pub mod prompt_surface;
pub mod provider;
pub mod ralph;
pub mod retrieval;
pub mod runner;
pub mod server;
pub mod session;
pub mod skills;
pub mod streaming;
pub mod telemetry;
pub mod text;
pub mod theme;
pub mod todos;
pub mod tool_policy;
pub mod tool_surface;
#[cfg(test)]
mod tool_surface_tests;
pub mod tools;
pub mod tui;
pub mod tui_keys;
pub mod tui_restore;
pub mod tui_text;
pub mod workflow;

#[cfg(test)]
mod tests;
