//! Shared deterministic fixtures for crate-level unit tests.

use crate::cli::{GuardrailMode, Provider, RetrievalBackend, SessionBackend, ToolConfirmationMode};
use crate::config::{AgentSource, RuntimeConfig};

pub(crate) fn base_cfg() -> RuntimeConfig {
    RuntimeConfig {
        profile: "default".to_string(),
        config_path: ".zavora/config.toml".to_string(),
        agent_name: "default".to_string(),
        agent_source: AgentSource::Implicit,
        agent_description: Some("Built-in default assistant".to_string()),
        agent_instruction: None,
        agent_resource_paths: Vec::new(),
        agent_allow_tools: Vec::new(),
        agent_deny_tools: Vec::new(),
        agent_allow_skills: Vec::new(),
        agent_deny_skills: Vec::new(),
        agent_allow_agents: Vec::new(),
        agent_deny_agents: Vec::new(),
        agent_max_turns: None,
        agent_timeout_secs: None,
        available_agents: crate::config::implicit_agent_map().into_values().collect(),
        hooks: std::collections::HashMap::new(),
        provider: Provider::Auto,
        model: None,
        worker_provider: Provider::Openai,
        worker_model: crate::model_catalog::DEFAULT_WORKER_MODEL.to_string(),
        planner_provider: Provider::Openai,
        planner_model: crate::model_catalog::DEFAULT_PLANNER_MODEL.to_string(),
        planner_call_budget: 4,
        api_key: None,
        ollama_host: None,
        app_name: "test-app".to_string(),
        user_id: "test-user".to_string(),
        session_id: "test-session".to_string(),
        session_backend: SessionBackend::Memory,
        session_db_url: "sqlite://.zavora/test.db".to_string(),
        show_sensitive_config: false,
        retrieval_backend: RetrievalBackend::Disabled,
        retrieval_doc_path: None,
        retrieval_max_chunks: 3,
        retrieval_max_chars: 4000,
        retrieval_min_score: 1,
        tool_confirmation_mode: ToolConfirmationMode::McpOnly,
        require_confirm_tool: Vec::new(),
        approve_tool: Vec::new(),
        tool_timeout_secs: 45,
        tool_retry_attempts: 2,
        tool_retry_delay_ms: 500,
        telemetry_enabled: false,
        telemetry_path: ".zavora/test-telemetry.jsonl".to_string(),
        guardrail_input_mode: GuardrailMode::Disabled,
        guardrail_output_mode: GuardrailMode::Disabled,
        guardrail_terms: vec!["secret".to_string(), "password".to_string()],
        guardrail_redact_replacement: "[REDACTED]".to_string(),
        mcp_servers: Vec::new(),
        permission_rules: Default::default(),
        max_prompt_chars: 32_000,
        server_runner_cache_max: 64,
        auto_compact_enabled: true,
        compact_interval: 10,
        compact_overlap: 2,
        compaction_threshold: 0.75,
        compaction_target: 0.10,
    }
}
